services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile.pg
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
      - api

volumes:
  postgres-volume: