services:
  postgres:
    image: postgis/postgis
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
      - api
      - openssl

volumes:
  postgres-volume:
  ssl-certs: